Linear Regression

In [34]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [35]:
df = pd.read_csv("/content/hiring.csv")
df.head(10)

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   experience                  6 non-null      object
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64
 3   salary($)                   8 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 388.0+ bytes

In [37]:
df.isna().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [38]:
import math
mn = math.floor(df['test_score(out of 10)'].mean())
mn

7

In [39]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(mn)
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [40]:
!pip install word2number

Requirement already satisfied: word2number in /usr/local/lib/python3.12/dist-packages (1.1)

In [41]:
from word2number import w2n
df.experience = df.experience.fillna("zero")
df.experience = df.experience.apply(w2n.word_to_num)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [42]:
df.rename(columns={'test_score(out of 10)': 'test_score', 'interview_score(out of 10)': 'interview_score', 'salary($)': 'salary'}, inplace=True)
df

   experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         7.0                7   72000
7          11         7.0                8   80000

In [43]:
X = df[['experience', 'test_score', 'interview_score']]
y = df['salary']

reg = linear_model.LinearRegression()
reg.fit(X, y)

LinearRegression()

In [44]:
prediction = reg.predict([[2, 9, 6]])[0]
print(f"Predicted salary for a candidate with 2 years experience, 9 test score, and 6 interview score: ${prediction:,.2f}")

Predicted salary for a candidate with 2 years experience, 9 test score, and 6 interview score: $53,713.87

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [45]:
import joblib
joblib.dump(reg, 'model_hiring.pkl')

print("Linear Regression model saved as 'model_hiring.pkl'")

Linear Regression model saved as 'model_hiring.pkl'

In [46]:
import joblib
import pickle

with open('model_hiring.pkl', 'rb') as file:
  model = joblib.load(file)

with open('hiring_model.pkl', 'wb') as file_to_save:
  pickle.dump(model, file_to_save)