In [2]:
from sklearn.datasets import load_wine
wine = load_wine()

In [3]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [4]:
import pandas as pd
df = pd.DataFrame(wine.data)
df.head()

      0     1     2     3      4     5   ...    7     8     9     10    11      12
0  14.23  1.71  2.43  15.6  127.0  2.80  ...  0.28  2.29  5.64  1.04  3.92  1065.0
1  13.20  1.78  2.14  11.2  100.0  2.65  ...  0.26  1.28  4.38  1.05  3.40  1050.0
2  13.16  2.36  2.67  18.6  101.0  2.80  ...  0.30  2.81  5.68  1.03  3.17  1185.0
3  14.37  1.95  2.50  16.8  113.0  3.85  ...  0.24  2.18  7.80  0.86  3.45  1480.0
4  13.24  2.59  2.87  21.0  118.0  2.80  ...  0.39  1.82  4.32  1.04  2.93   735.0

[5 rows x 13 columns]

In [5]:
df['target'] = wine.target
df.head(5)

       0     1     2     3      4     5  ...     8     9    10    11      12  target
0  14.23  1.71  2.43  15.6  127.0  2.80  ...  2.29  5.64  1.04  3.92  1065.0       0
1  13.20  1.78  2.14  11.2  100.0  2.65  ...  1.28  4.38  1.05  3.40  1050.0       0
2  13.16  2.36  2.67  18.6  101.0  2.80  ...  2.81  5.68  1.03  3.17  1185.0       0
3  14.37  1.95  2.50  16.8  113.0  3.85  ...  2.18  7.80  0.86  3.45  1480.0       0
4  13.24  2.59  2.87  21.0  118.0  2.80  ...  1.82  4.32  1.04  2.93   735.0       0

[5 rows x 14 columns]

In [6]:
for i in range(10):
    wine['feature_names']

In [7]:
x = df.drop('target', axis = 'columns')
y = df['target']
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.2, shuffle=True, random_state=1)

In [8]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [29]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [30]:
xtrain.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
91,12.00,1.51,2.42,22.0,86.0,1.45,1.25,0.50,1.63,3.60,1.05,2.65,450.0
81,12.72,1.81,2.20,18.8,86.0,2.20,2.53,0.26,1.77,3.90,1.16,3.14,714.0
114,12.08,1.39,2.50,22.5,84.0,2.56,2.29,0.43,1.04,2.90,0.93,3.19,385.0
48,14.10,2.02,2.40,18.8,103.0,2.75,2.92,0.32,2.38,6.20,1.07,2.75,1060.0
54,13.74,1.67,2.25,16.4,118.0,2.60,2.90,0.21,1.62,5.85,0.92,3.20,1060.0

In [31]:
ytrain.head()

91     1
81     1
114    1
48     0
54     0
Name: target, dtype: int64

In [32]:
model.fit(xtrain, ytrain)

GaussianNB()

In [33]:
model.predict(xtest)

array([2, 1, 0, 1, 0, 2, 1, 0, 2, 1, 0, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 1,
       2, 1, 0, 2, 0, 0, 0, 2, 1, 2, 2, 0, 1, 1])

In [34]:
model.score(xtest, ytest)

1.0

In [35]:
import pickle
with open('GaussianNB_model.pkl', 'wb') as file:
    pickle.dump(model, file)

In [1]:
from sklearn.naive_bayes import MultinomialNB
model1 = MultinomialNB()

In [9]:
model1.fit(xtrain, ytrain)

MultinomialNB()

In [10]:
model1.predict(xtest)

array([2, 1, 0, 1, 0, 2, 1, 0, 2, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 2, 1, 2, 1, 0, 1, 1])

In [11]:
model1.score(xtest, ytest)

0.8333333333333334

In [12]:
import pickle
with open('MultinomialNB_model.pkl', 'wb') as file:
    pickle.dump(model1, file)